/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.6 and Signal Processing Toolbox 8.2.
 * Generated on: 17-Nov-2022 19:30:04
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 61
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2019a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int32 filter coefficients.
 */
const int BL5 = 61;
const int32_T B5[61] = {
       5026618,     5205860,     5703131,     6516687,     7641017,     9066886,
      10781416,    12768223,    15007584,    17476660,    20149748,    22998571,
      25992606,    29099435,    32285121,    35514610,    38752140,    41961665,
      45107285,    48153671,    51066487,    53812803,    56361489,    58683588,
      60752666,    62545130,    64040512,    65221718,    66075233,    66591284,
      66763960,    66591284,    66075233,    65221718,    64040512,    62545130,
      60752666,    58683588,    56361489,    53812803,    51066487,    48153671,
      45107285,    41961665,    38752140,    35514610,    32285121,    29099435,
      25992606,    22998571,    20149748,    17476660,    15007584,    12768223,
      10781416,     9066886,     7641017,     6516687,     5703131,     5205860,
       5026618
};
